### ISSUE TITLE
Unable to cast object of type 'OPCAutomation.OPCServerClass' 

### ISSUE THREAD

**Issue by AmirGhased71** [iioter/iotgateway#51]
Hi sam,and all friends,
I have an OPC.Da.The server for the KEBA company is named Kestudio.
I connected to it with the Kebserver software and there is no problem.
but Error in IoTGateway master:

Unable to cast object of type 'OPCAutomation.OPCServerClass' to type 'OPCAutomation.IOPCGroups'.

   at System.StubHelpers.InterfaceMarshaler.ConvertToManaged(IntPtr& ppUnk, IntPtr itfMT, IntPtr classMT, Int32 flags)
   at OPCAutomation.OPCServerClass.get_OPCGroups()
   at Automation.OPCClient.OPCClientWrapper.Init(String serverIP, String opcServerName) in E:\Project\IoTGateway\Plugins\Drivers\OPC.DaClient\OPCClient\OPCClientWrapper.cs:line 132

Please help me,
Thanks

![Screenshot 2024-12-01 122901](https://github.com/user-attachments/assets/b7a660ed-9e89-4c7a-9446-2a131c6c1e68)

**Comment by iioter** [comment]
Hi, can you send the software  'OPC.Da.The server for the KEBA company is named Kestudio' to my email?

**Comment by iioter** [comment]
It is true that iotgateway cannot connect to KeStudio.Opc, and the enterprise version can be connected through other solutions, but the open source version is not available yet.
